FROM node:latest AS build
WORKDIR /app

# installing the network tools for debugging
RUN apt-get update 
RUN apt-get install -y net-tools lsof

# Getting all the files in the container
COPY . .

# making sure that the dist, and node_modules folders are not present
RUN rm -rf dist/
RUN rm -rf node_modules/

# installing the dependencies and building the app
RUN npm install
RUN npm run build

# opening the port
EXPOSE 4173

# starting the app
CMD [ "npm", "run", "preview" ] 
